# Generated by Django 5.0.6 on 2024-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
