# Generated by Django 5.0.6 on 2024-05-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('famille', models.CharField(max_length=24)),
                ('classe', models.CharField(max_length=24)),
                ('type_uniter', models.CharField(max_length=25)),
                ('type_gros', models.CharField(max_length=25)),
                ('qte_max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=20)),
                ('adress', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('provenance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AjoutStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_uniter_transaction', models.IntegerField()),
                ('qte_gros_transaction', models.IntegerField(default=0, null=True)),
                ('type_transaction', models.TextField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('reste', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_gros', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_uniter', models.DecimalField(decimal_places=0, max_digits=10)),
                ('qte_uniter', models.IntegerField(default=0, null=True)),
                ('qte_gros', models.IntegerField(default=0, null=True)),
                ('date_peremption', models.DateField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajout_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='stock.ajoutstock')),
                ('detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.detail')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.fournisseur')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.marque')),
            ],
        ),
        migrations.CreateModel(
            name='VenteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_uniter_transaction', models.IntegerField()),
                ('qte_gros_transaction', models.IntegerField(default=0, null=True)),
                ('type_transaction', models.TextField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.product')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
