# Generated by Django 5.0.6 on 2024-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=20),
        ),
    ]
