# Generated by Django 5.0.6 on 2024-05-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_fournisseur_contact_alter_fournisseur_nom'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('fournisseur', 'marque', 'detail'), name='unique_fournisseur_marque_detail'),
        ),
    ]
