# Generated by Django 5.0.6 on 2024-05-19 18:12

from django.db import migrations
import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20240519_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('famille', models.CharField(max_length=24)),
                ('classe', models.CharField(max_length=24)),
                ('type_uniter', models.CharField(max_length=25)),
                ('type_gros', models.CharField(max_length=25)),
                ('marque', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_uniter', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_gros', models.DecimalField(decimal_places=0, max_digits=10)),
                ('qte_uniter', models.IntegerField(default=0, null=True)),
                ('qte_gros', models.IntegerField(default=0, null=True)),
                ('date_peremption', models.DateField()),
                ('date_ajout', models.DateTimeField(default= django.utils.timezone.now)),
                ('detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.detail')),
            ],
        ),
    ]
