# Generated by Django 5.0.6 on 2024-05-25 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20240519_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='qte_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
