# Generated by Django 5.0.6 on 2024-05-26 12:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_detail_qte_max_alter_product_date_ajout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=20)),
                ('adress', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AjoutStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_transaction', models.IntegerField()),
                ('type_transaction', models.TextField(max_length=25)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 26, 12, 59, 33, 638023, tzinfo=datetime.timezone.utc))),
                ('complete', models.BooleanField(default=False)),
                ('reste', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ajout_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='stock.ajoutstock'),
        ),
        migrations.CreateModel(
            name='VenteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_transaction', models.IntegerField()),
                ('type_transaction', models.TextField(max_length=25)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 26, 12, 59, 33, 638023, tzinfo=datetime.timezone.utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.product')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
