# Generated by Django 5.0.6 on 2024-05-26 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_ajoutstock_qte_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajoutstock',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 26, 13, 4, 56, 628160, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ajoutstock',
            name='qte_gros_transaction',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ajoutstock',
            name='qte_uniter_transaction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventestock',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 26, 13, 4, 56, 628160, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ventestock',
            name='qte_gros_transaction',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ventestock',
            name='qte_uniter_transaction',
            field=models.IntegerField(),
        ),
    ]
